### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by frederikbosch** [veewee/xml#62]
I see my [genkgo/xsl](https://github.com/genkgo/xsl) packages was on your roadmap. Too bad you didn't choose to use it ;). 

Anyhow, since the number of XML/XSL dev in PHP is small, I do wanted to let you know that I am following the [XRust project](https://github.com/ballsteve/xrust) with interest. While it may seem not too active, do have a look at other branches than the main branch. To me that project is very promising, and combined with the [PHP Enjoy Rust framework](https://github.com/phper-framework/phper) we can actually get XSL 2.0+ implemented in a good manner. You might consider to have that on your roadmap rather than my package or Saxon C.

**Comment by veewee** [comment]
Thanks for reaching out @frederikbosch.

This package currently only supports the native PHP XML extensions. I decided not to go for 3rth party packages or extensions (_yet_) to keep it more lightweight. I'm sure your xslt2 packge is spot on but was looking at saxon because it also provides (on top of xslt2) a lot more 'newer' XML stuff that are not supported by PHP by default. That way, I only need to care about one extension and one point of failure. What holds me back a bit, is that people need an additional 3rd party PECL extension in order to use those functions that I consider rather "basic".

It would be extremely nice if we would get more "recent" versions of xpath, xslt, ... directly from PHP, but I don't see that happening anytime soon. 

I'm gonna look into the XRust project later on, thanks for putting it on my radar! If I were to use that one here, it would still require either a PHP extesion or FFI bindings that need to get compiled for the target systems. It kinda feels like additional (very painly) steps that people need to take in order to work with XML, which is a bit sad from my point of view. 

Don't get me wrong here: This package is open-source and it is open for improvements and additional features. I'm all in for adding better functionalities - but I've seen a lot of pain implementing this library already, so I would love to keep things as simple/standard as possible :) 

If you feel like you are missing something in here: feel free to propose concrete implementations.

Looking forward for collaborating! :)

**Comment by frederikbosch** [comment]
Totally get all your points. It would indeed be nice if we would get it from PHP, but I am already happy to see there is now someone now focusing on bugfixes in the DOM extension and adding some small improvements. Good luck with your project. It looks very nice. I will let you know when I have some updates on XML related stuff. Goede avond!
